/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_devflow_devflow_answer_parameter_0$schema = z.object({
  'itemId': z.string().readonly(),
  'stage': z.union([z.literal(null), z.literal("design"), z.literal("plan"), z.literal("review-dp"), z.literal("implement"), z.literal("code-review"), z.literal("fix-code"), z.literal("verify"), z.literal("merge"), z.literal("report")]).readonly(),
  'answers': z.array(z.object({
  'q': z.string().readonly(),
  'a': z.string().readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_devflow_devflow_answer_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_devflow_devflow_artifact_parameter_0$schema = z.object({
  'itemId': z.string().readonly(),
  'name': z.union([z.literal("design"), z.literal("plan"), z.literal("report"), z.literal("reviews")]).readonly(),
})
const _deepseek_ai_dsh_devflow_devflow_artifact_result$schema = z.string()
const _deepseek_ai_dsh_devflow_devflow_cancel_parameter_0$schema = z.object({
  'itemId': z.string(),
})
const _deepseek_ai_dsh_devflow_devflow_cancel_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_devflow_devflow_prompt_set_parameter_0$schema = z.object({
  'stage': z.string().readonly(),
  'template': z.union([z.literal(null), z.string()]).readonly(),
})
const _deepseek_ai_dsh_devflow_devflow_prompt_set_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_devflow_devflow_prompts_result$schema = z.object({
  'custom': z.record(z.string(), z.string()).readonly(),
  'defaults': z.record(z.string(), z.string()).readonly(),
  'vars': z.record(z.string(), z.array(z.string())).readonly(),
})
const _deepseek_ai_dsh_devflow_devflow_resume_parameter_0$schema = z.object({
  'itemId': z.string(),
})
const _deepseek_ai_dsh_devflow_devflow_resume_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_devflow_devflow_retry_parameter_0$schema = z.object({
  'itemId': z.string(),
})
const _deepseek_ai_dsh_devflow_devflow_retry_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.string().readonly().optional(),
})
const _deepseek_ai_dsh_devflow_devflow_state_result$schema = z.object({
  'busy': z.boolean().readonly(),
  'note': z.union([z.literal(null), z.string()]).readonly(),
  'error': z.union([z.literal(null), z.string()]).readonly(),
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'kind': z.union([z.literal("requirement"), z.literal("bug")]).readonly(),
  'title': z.string().readonly(),
  'status': z.union([z.literal("rejected"), z.literal("raw"), z.literal("refining"), z.literal("needs-user"), z.literal("ready"), z.literal("active"), z.literal("done"), z.literal("paused")]).readonly(),
  'size': z.union([z.literal(null), z.literal("small"), z.literal("medium"), z.literal("large")]).readonly(),
  'score': z.union([z.literal(null), z.object({
  'value': z.number().readonly(),
  'completeness': z.number().readonly(),
})]).readonly(),
  'running': z.boolean().readonly(),
  'note': z.union([z.literal(null), z.string()]).readonly(),
  'preview': z.string().readonly(),
  'rejectReason': z.string().readonly(),
  'questions': z.union([z.literal(null), z.array(z.object({
  'id': z.string().readonly().optional(),
  'q': z.string().readonly(),
  'options': z.array(z.object({
  'label': z.string().readonly(),
  'desc': z.string().readonly(),
})).readonly(),
  'recommend': z.string().readonly().optional(),
}))]).readonly(),
  'waitingStage': z.union([z.literal(null), z.literal("design"), z.literal("plan"), z.literal("review-dp"), z.literal("implement"), z.literal("code-review"), z.literal("fix-code"), z.literal("verify"), z.literal("merge"), z.literal("report")]).readonly(),
  'stage': z.union([z.literal(null), z.literal("design"), z.literal("plan"), z.literal("review-dp"), z.literal("implement"), z.literal("code-review"), z.literal("fix-code"), z.literal("verify"), z.literal("merge"), z.literal("report")]).readonly(),
  'round': z.number().readonly(),
  'error': z.union([z.literal(null), z.string()]).readonly(),
  'workspaceKind': z.union([z.literal(null), z.literal("main"), z.literal("worktree")]).readonly(),
  'workspacePath': z.union([z.literal(null), z.string()]).readonly(),
  'workspaceBranch': z.union([z.literal(null), z.string()]).readonly(),
  'resourceWaiting': z.union([z.literal(null), z.literal("worktree"), z.literal("workspace")]).readonly(),
  'reportFile': z.union([z.literal(null), z.string()]).readonly(),
  'log': z.array(z.object({
  'n': z.number().readonly(),
  'note': z.string().readonly(),
})).readonly(),
})).readonly(),
})
const _deepseek_ai_dsh_devflow_devflow_submit_parameter_0$schema = z.object({
  'kind': z.union([z.literal("requirement"), z.literal("bug")]).readonly(),
  'text': z.string().readonly(),
})
const _deepseek_ai_dsh_devflow_devflow_submit_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'id': z.string().readonly(),
})

export const TYPERT = {
  package: 'dsh-devflow',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-devflow#devflow/answer',
      service: 'devflow',
      namespace: 'devflow',
      method: 'answer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowAnswerRequest',
            schema: _deepseek_ai_dsh_devflow_devflow_answer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: _deepseek_ai_dsh_devflow_devflow_answer_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/devflow/src/index.ts","line":216,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/artifact',
      service: 'devflow',
      namespace: 'devflow',
      method: 'artifact',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowArtifactRequest',
            schema: _deepseek_ai_dsh_devflow_devflow_artifact_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow#devflow/artifact:result',
        schema: _deepseek_ai_dsh_devflow_devflow_artifact_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/devflow/src/index.ts","line":311,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/cancel',
      service: 'devflow',
      namespace: 'devflow',
      method: 'cancel',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow#devflow/cancel:request',
            schema: _deepseek_ai_dsh_devflow_devflow_cancel_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: _deepseek_ai_dsh_devflow_devflow_cancel_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/devflow/src/index.ts","line":245,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/prompt-set',
      service: 'devflow',
      namespace: 'devflow',
      method: 'prompt-set',
      implementation: 'promptSet',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowPromptSetRequest',
            schema: _deepseek_ai_dsh_devflow_devflow_prompt_set_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: _deepseek_ai_dsh_devflow_devflow_prompt_set_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/devflow/src/index.ts","line":333,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/prompts',
      service: 'devflow',
      namespace: 'devflow',
      method: 'prompts',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowPromptsView',
        schema: _deepseek_ai_dsh_devflow_devflow_prompts_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/devflow/src/index.ts","line":326,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/resume',
      service: 'devflow',
      namespace: 'devflow',
      method: 'resume',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow#devflow/resume:request',
            schema: _deepseek_ai_dsh_devflow_devflow_resume_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: _deepseek_ai_dsh_devflow_devflow_resume_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/devflow/src/index.ts","line":278,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/retry',
      service: 'devflow',
      namespace: 'devflow',
      method: 'retry',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow#devflow/retry:request',
            schema: _deepseek_ai_dsh_devflow_devflow_retry_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: _deepseek_ai_dsh_devflow_devflow_retry_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/devflow/src/index.ts","line":293,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/state',
      service: 'devflow',
      namespace: 'devflow',
      method: 'state',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowView',
        schema: _deepseek_ai_dsh_devflow_devflow_state_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/devflow/src/index.ts","line":181,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/submit',
      service: 'devflow',
      namespace: 'devflow',
      method: 'submit',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowSubmitRequest',
            schema: _deepseek_ai_dsh_devflow_devflow_submit_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowSubmitResult',
        schema: _deepseek_ai_dsh_devflow_devflow_submit_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/devflow/src/index.ts","line":188,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "The pipeline service. One process-local tick loop owns every state mutation; a busy flag serializes ticks, and per-call AbortControllers forward panel cancels into in-flight model streams.",
        "summary": "The pipeline service.",
        "tags": [],
        "jsDoc": "/**\n * The pipeline service. One process-local tick loop owns every state\n * mutation; a busy flag serializes ticks, and per-call AbortControllers\n * forward panel cancels into in-flight model streams.\n */",
        "key": "devflow",
        "exportName": "DevflowService",
        "members": [
          {
            "kind": "method",
            "name": "state",
            "signature": "@Remote('state') async state(): Promise<DevflowView>",
            "summary": "Whole-state projection the panel polls.",
            "jsDoc": "/** Whole-state projection the panel polls. */"
          },
          {
            "kind": "method",
            "name": "submit",
            "signature": "@Remote('submit') async submit(request: DevflowSubmitRequest): Promise<DevflowSubmitResult>",
            "summary": "Drop one raw requirement or bug into the pool.",
            "jsDoc": "/** Drop one raw requirement or bug into the pool. */"
          },
          {
            "kind": "method",
            "name": "answer",
            "signature": "@Remote('answer') async answer(request: DevflowAnswerRequest): Promise<DevflowMutationResult>",
            "summary": "Answer waiting-queue or refinement questions.",
            "jsDoc": "/** Answer waiting-queue or refinement questions. */"
          },
          {
            "kind": "method",
            "name": "cancel",
            "signature": "@Remote('cancel') async cancel(request: { itemId: string }): Promise<DevflowMutationResult>",
            "summary": "Interrupt execution or collapse a waiting entry into a real pause.",
            "jsDoc": "/** Interrupt execution or collapse a waiting entry into a real pause. */"
          },
          {
            "kind": "method",
            "name": "resume",
            "signature": "@Remote('resume') async resume(request: { itemId: string }): Promise<DevflowMutationResult>",
            "summary": "Resume a paused item back into its pre-interruption lane.",
            "jsDoc": "/** Resume a paused item back into its pre-interruption lane. */"
          },
          {
            "kind": "method",
            "name": "retry",
            "signature": "@Remote('retry') async retry(request: { itemId: string }): Promise<DevflowMutationResult>",
            "summary": "Clear one item's sticky stage error (or refine cooldown).",
            "jsDoc": "/** Clear one item's sticky stage error (or refine cooldown). */"
          },
          {
            "kind": "method",
            "name": "artifact",
            "signature": "@Remote('artifact') async artifact(request: DevflowArtifactRequest): Promise<string>",
            "summary": "Read one artifact's (clipped) text for the panel viewer.",
            "jsDoc": "/** Read one artifact's (clipped) text for the panel viewer. */"
          },
          {
            "kind": "method",
            "name": "prompts",
            "signature": "@Remote('prompts') async prompts(): Promise<DevflowPromptsView>",
            "summary": "Prompt-template directory: defaults plus the user's overrides.",
            "jsDoc": "/** Prompt-template directory: defaults plus the user's overrides. */"
          },
          {
            "kind": "method",
            "name": "promptSet",
            "signature": "@Remote('prompt-set') async promptSet(request: DevflowPromptSetRequest): Promise<DevflowMutationResult>",
            "summary": "Set (or clear with null) one stage's custom template.",
            "jsDoc": "/** Set (or clear with null) one stage's custom template. */"
          }
        ],
        "types": [
          {
            "name": "DevflowAnswer",
            "declaration": "export interface DevflowAnswer {\n    readonly q: string;\n    readonly a: string;\n}"
          },
          {
            "name": "DevflowAnswerRequest",
            "declaration": "export interface DevflowAnswerRequest {\n    readonly itemId: string;\n    readonly stage: DevflowStage | null;\n    readonly answers: readonly DevflowAnswer[];\n}"
          },
          {
            "name": "DevflowArtifactRequest",
            "declaration": "export interface DevflowArtifactRequest {\n    readonly itemId: string;\n    readonly name: 'design' | 'plan' | 'report' | 'reviews';\n}"
          },
          {
            "name": "DevflowItemStatus",
            "declaration": "export type DevflowItemStatus = 'raw' | 'refining' | 'needs-user' | 'ready' | 'active' | 'done' | 'rejected' | 'paused';"
          },
          {
            "name": "DevflowItemView",
            "declaration": "export interface DevflowItemView {\n    readonly id: string;\n    readonly kind: 'requirement' | 'bug';\n    readonly title: string;\n    readonly status: DevflowItemStatus;\n    readonly size: DevflowSize | null;\n    readonly score: DevflowScore | null;\n    readonly running: boolean;\n    readonly note: string | null;\n    readonly preview: string;\n    readonly rejectReason: string;\n    readonly questions: readonly DevflowQuestion[] | null;\n    readonly waitingStage: DevflowStage | null;\n    readonly stage: DevflowStage | null;\n    readonly round: number;\n    readonly error: string | null;\n    readonly workspaceKind: 'main' | 'worktree' | null;\n    readonly workspacePath: string | null;\n    readonly workspaceBranch: string | null;\n    readonly resourceWaiting: 'workspace' | 'worktree' | null;\n    readonly reportFile: string | null;\n    readonly log: readonly DevflowLogLine[];\n}"
          },
          {
            "name": "DevflowLogLine",
            "declaration": "export interface DevflowLogLine {\n    readonly n: number;\n    readonly note: string;\n}"
          },
          {
            "name": "DevflowMutationResult",
            "declaration": "export interface DevflowMutationResult {\n    readonly ok: boolean;\n    readonly reason?: string;\n}"
          },
          {
            "name": "DevflowPromptSetRequest",
            "declaration": "export interface DevflowPromptSetRequest {\n    readonly stage: string;\n    readonly template: string | null;\n}"
          },
          {
            "name": "DevflowPromptsView",
            "declaration": "export interface DevflowPromptsView {\n    readonly custom: Record<string, string>;\n    readonly defaults: Record<string, string>;\n    readonly vars: Record<string, readonly string[]>;\n}"
          },
          {
            "name": "DevflowQuestion",
            "declaration": "export interface DevflowQuestion {\n    readonly id?: string;\n    readonly q: string;\n    readonly options: readonly DevflowQuestionOption[];\n    readonly recommend?: string;\n}"
          },
          {
            "name": "DevflowQuestionOption",
            "declaration": "export interface DevflowQuestionOption {\n    readonly label: string;\n    readonly desc: string;\n}"
          },
          {
            "name": "DevflowScore",
            "declaration": "export interface DevflowScore {\n    readonly value: number;\n    readonly completeness: number;\n}"
          },
          {
            "name": "DevflowSize",
            "declaration": "export type DevflowSize = 'small' | 'medium' | 'large';"
          },
          {
            "name": "DevflowStage",
            "declaration": "export type DevflowStage = 'design' | 'plan' | 'review-dp' | 'implement' | 'code-review' | 'fix-code' | 'verify' | 'merge' | 'report';"
          },
          {
            "name": "DevflowSubmitRequest",
            "declaration": "export interface DevflowSubmitRequest {\n    readonly kind: 'requirement' | 'bug';\n    readonly text: string;\n}"
          },
          {
            "name": "DevflowSubmitResult",
            "declaration": "export interface DevflowSubmitResult {\n    readonly ok: boolean;\n    readonly id: string;\n}"
          },
          {
            "name": "DevflowView",
            "declaration": "export interface DevflowView {\n    readonly busy: boolean;\n    readonly note: string | null;\n    readonly error: string | null;\n    readonly items: readonly DevflowItemView[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
