/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { DevflowAnswerRequest, DevflowArtifactRequest, DevflowMutationResult, DevflowPromptSetRequest, DevflowPromptsView, DevflowSubmitRequest, DevflowSubmitResult, DevflowView } from 'dsh-devflow/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$646576666c6f77 {
    answer: (request: DevflowAnswerRequest) => Promise<RemoteResult<DevflowMutationResult>>
    artifact: (request: DevflowArtifactRequest) => Promise<RemoteResult<string>>
    cancel: (request: { itemId: string; }) => Promise<RemoteResult<DevflowMutationResult>>
    'prompt-set': (request: DevflowPromptSetRequest) => Promise<RemoteResult<DevflowMutationResult>>
    prompts: () => Promise<RemoteResult<DevflowPromptsView>>
    resume: (request: { itemId: string; }) => Promise<RemoteResult<DevflowMutationResult>>
    retry: (request: { itemId: string; }) => Promise<RemoteResult<DevflowMutationResult>>
    state: () => Promise<RemoteResult<DevflowView>>
    submit: (request: DevflowSubmitRequest) => Promise<RemoteResult<DevflowSubmitResult>>
  }
  interface TypertRemoteMap {
    'devflow/answer': (request: DevflowAnswerRequest) => Promise<RemoteResult<DevflowMutationResult>>
    'devflow/artifact': (request: DevflowArtifactRequest) => Promise<RemoteResult<string>>
    'devflow/cancel': (request: { itemId: string; }) => Promise<RemoteResult<DevflowMutationResult>>
    'devflow/prompt-set': (request: DevflowPromptSetRequest) => Promise<RemoteResult<DevflowMutationResult>>
    'devflow/prompts': () => Promise<RemoteResult<DevflowPromptsView>>
    'devflow/resume': (request: { itemId: string; }) => Promise<RemoteResult<DevflowMutationResult>>
    'devflow/retry': (request: { itemId: string; }) => Promise<RemoteResult<DevflowMutationResult>>
    'devflow/state': () => Promise<RemoteResult<DevflowView>>
    'devflow/submit': (request: DevflowSubmitRequest) => Promise<RemoteResult<DevflowSubmitResult>>
  }
  interface TypertRemoteNamespaceMap {
    'devflow': TypertRemoteNamespace$646576666c6f77
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
