/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const dsh_devflow_devflow_answer_parameter_0$schema = z.object({
  'itemId': z.string().readonly(),
  'stage': z.union([z.literal(null), z.literal("design"), z.literal("plan"), z.literal("review-dp"), z.literal("implement"), z.literal("code-review"), z.literal("fix-code"), z.literal("verify"), z.literal("merge"), z.literal("report")]).readonly(),
  'answers': z.array(z.object({
  'q': z.string().readonly(),
  'a': z.string().readonly(),
})).readonly(),
})
const dsh_devflow_devflow_answer_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const dsh_devflow_devflow_artifact_parameter_0$schema = z.object({
  'itemId': z.string().readonly(),
  'name': z.union([z.literal("design"), z.literal("plan"), z.literal("report"), z.literal("reviews")]).readonly(),
})
const dsh_devflow_devflow_artifact_result$schema = z.string()
const dsh_devflow_devflow_cancel_parameter_0$schema = z.object({
  'itemId': z.string(),
})
const dsh_devflow_devflow_cancel_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const dsh_devflow_devflow_config_get_parameter_0$schema = z.object({
  'project': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_devflow_devflow_config_get_result$schema = z.object({
  'settings': z.object({
  'version': z.literal(1).readonly(),
  'stageModels': z.record(z.string(), z.string()).readonly().readonly(),
  'pump': z.union([z.undefined(), z.object({
  'enabled': z.boolean().readonly(),
  'model': z.string().readonly(),
})]).readonly().optional(),
}).readonly(),
  'warnings': z.array(z.string()).readonly(),
})
const dsh_devflow_devflow_config_models_parameter_0$schema = z.object({
  'project': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_devflow_devflow_config_models_result$schema = z.array(z.object({
  'id': z.string().readonly(),
  'label': z.string().readonly(),
}))
const dsh_devflow_devflow_config_set_parameter_0$schema = z.object({
  'project': z.union([z.literal(null), z.string()]).readonly(),
  'settings': z.object({
  'version': z.literal(1).readonly(),
  'stageModels': z.record(z.string(), z.string()).readonly().readonly(),
  'pump': z.union([z.undefined(), z.object({
  'enabled': z.boolean().readonly(),
  'model': z.string().readonly(),
})]).readonly().optional(),
}).readonly(),
})
const dsh_devflow_devflow_config_set_result$schema = z.object({
  'version': z.literal(1).readonly(),
  'stageModels': z.record(z.string(), z.string()).readonly().readonly(),
  'pump': z.union([z.undefined(), z.object({
  'enabled': z.boolean().readonly(),
  'model': z.string().readonly(),
})]).readonly().optional(),
})
const dsh_devflow_devflow_project_add_parameter_0$schema = z.object({
  'path': z.string().readonly(),
})
const dsh_devflow_devflow_project_add_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.union([z.undefined(), z.string()]).readonly().optional(),
  'key': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_devflow_devflow_project_list_dir_parameter_0$schema = z.object({
  'path': z.union([z.literal(null), z.string()]),
})
const dsh_devflow_devflow_project_list_dir_result$schema = z.object({
  'path': z.string().readonly(),
  'home': z.string().readonly(),
  'crumbs': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'hidden': z.boolean().readonly(),
})).readonly(),
  'entries': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'hidden': z.boolean().readonly(),
})).readonly(),
  'truncated': z.boolean().readonly(),
})
const dsh_devflow_devflow_project_pick_capability_result$schema = z.object({
  'kind': z.union([z.literal("native"), z.literal("browse"), z.literal("none")]).readonly(),
})
const dsh_devflow_devflow_project_pick_native_result$schema = z.object({
  'path': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_devflow_devflow_project_remove_parameter_0$schema = z.object({
  'key': z.string().readonly(),
})
const dsh_devflow_devflow_project_remove_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const dsh_devflow_devflow_project_scan_parameter_0$schema = z.object({
  'rescan': z.boolean().readonly(),
})
const dsh_devflow_devflow_project_scan_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const dsh_devflow_devflow_prompt_set_parameter_0$schema = z.object({
  'stage': z.string().readonly(),
  'template': z.union([z.literal(null), z.string()]).readonly(),
  'project': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_devflow_devflow_prompt_set_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const dsh_devflow_devflow_prompts_parameter_0$schema = z.object({
  'project': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_devflow_devflow_prompts_result$schema = z.object({
  'custom': z.record(z.string(), z.string()).readonly(),
  'defaults': z.record(z.string(), z.string()).readonly(),
  'vars': z.record(z.string(), z.array(z.string())).readonly(),
})
const dsh_devflow_devflow_resume_parameter_0$schema = z.object({
  'itemId': z.string(),
})
const dsh_devflow_devflow_resume_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const dsh_devflow_devflow_retry_parameter_0$schema = z.object({
  'itemId': z.string(),
})
const dsh_devflow_devflow_retry_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'reason': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const dsh_devflow_devflow_state_parameter_0$schema = z.object({
  'project': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_devflow_devflow_state_result$schema = z.object({
  'busy': z.boolean().readonly(),
  'note': z.union([z.literal(null), z.string()]).readonly(),
  'error': z.union([z.literal(null), z.string()]).readonly(),
  'project': z.union([z.literal(null), z.string()]).readonly(),
  'projects': z.array(z.object({
  'key': z.string().readonly(),
  'name': z.string().readonly(),
  'root': z.string().readonly(),
  'origin': z.union([z.literal("workspace"), z.literal("scan"), z.literal("manual")]).readonly(),
})).readonly(),
  'ignoredRoots': z.array(z.string()).readonly(),
  'waitingTotal': z.number().readonly(),
  'pump': z.object({
  'enabled': z.boolean().readonly(),
  'available': z.boolean().readonly(),
  'activeCount': z.number().readonly(),
  'maxConcurrent': z.number().readonly(),
  'model': z.union([z.literal(null), z.string()]).readonly(),
}).readonly(),
  'items': z.array(z.object({
  'id': z.string().readonly(),
  'kind': z.union([z.literal("requirement"), z.literal("bug")]).readonly(),
  'title': z.string().readonly(),
  'status': z.union([z.literal("raw"), z.literal("refining"), z.literal("needs-user"), z.literal("ready"), z.literal("active"), z.literal("done"), z.literal("rejected"), z.literal("paused")]).readonly(),
  'size': z.union([z.literal(null), z.literal("small"), z.literal("medium"), z.literal("large")]).readonly(),
  'score': z.union([z.literal(null), z.object({
  'value': z.number().readonly(),
  'completeness': z.number().readonly(),
})]).readonly(),
  'running': z.boolean().readonly(),
  'note': z.union([z.literal(null), z.string()]).readonly(),
  'preview': z.string().readonly(),
  'rejectReason': z.string().readonly(),
  'questions': z.union([z.literal(null), z.array(z.object({
  'id': z.union([z.undefined(), z.string()]).readonly().optional(),
  'q': z.string().readonly(),
  'options': z.array(z.object({
  'label': z.string().readonly(),
  'desc': z.string().readonly(),
})).readonly(),
  'recommend': z.union([z.undefined(), z.string()]).readonly().optional(),
}))]).readonly(),
  'waitingStage': z.union([z.literal(null), z.literal("design"), z.literal("plan"), z.literal("review-dp"), z.literal("implement"), z.literal("code-review"), z.literal("fix-code"), z.literal("verify"), z.literal("merge"), z.literal("report")]).readonly(),
  'stage': z.union([z.literal(null), z.literal("design"), z.literal("plan"), z.literal("review-dp"), z.literal("implement"), z.literal("code-review"), z.literal("fix-code"), z.literal("verify"), z.literal("merge"), z.literal("report")]).readonly(),
  'round': z.number().readonly(),
  'error': z.union([z.literal(null), z.string()]).readonly(),
  'workspaceKind': z.union([z.literal(null), z.literal("main"), z.literal("worktree")]).readonly(),
  'workspacePath': z.union([z.literal(null), z.string()]).readonly(),
  'workspaceBranch': z.union([z.literal(null), z.string()]).readonly(),
  'resourceWaiting': z.union([z.literal(null), z.literal("workspace"), z.literal("worktree")]).readonly(),
  'reportFile': z.union([z.literal(null), z.string()]).readonly(),
  'pumpRunning': z.boolean().readonly(),
  'pumpWaitingUser': z.boolean().readonly(),
  'pumpWaitingApproval': z.boolean().readonly(),
  'pumpSessionId': z.union([z.literal(null), z.string()]).readonly(),
  'log': z.array(z.object({
  'n': z.number().readonly(),
  'note': z.string().readonly(),
})).readonly(),
})).readonly(),
})
const dsh_devflow_devflow_submit_parameter_0$schema = z.object({
  'kind': z.union([z.literal("requirement"), z.literal("bug")]).readonly(),
  'text': z.string().readonly(),
  'project': z.union([z.literal(null), z.string()]).readonly(),
})
const dsh_devflow_devflow_submit_result$schema = z.object({
  'ok': z.boolean().readonly(),
  'id': z.string().readonly(),
})

export const TYPERT = {
  package: 'dsh-devflow',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: 'dsh-devflow#devflow/answer',
      service: 'devflow',
      namespace: 'devflow',
      method: 'answer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowAnswerRequest',
            schema: dsh_devflow_devflow_answer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: dsh_devflow_devflow_answer_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":551,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/artifact',
      service: 'devflow',
      namespace: 'devflow',
      method: 'artifact',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowArtifactRequest',
            schema: dsh_devflow_devflow_artifact_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow#devflow/artifact:result',
        schema: dsh_devflow_devflow_artifact_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":646,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/cancel',
      service: 'devflow',
      namespace: 'devflow',
      method: 'cancel',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow#devflow/cancel:request',
            schema: dsh_devflow_devflow_cancel_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: dsh_devflow_devflow_cancel_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":579,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/config.get',
      service: 'devflow',
      namespace: 'devflow',
      method: 'config.get',
      implementation: 'configGet',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowStateRequest',
            schema: dsh_devflow_devflow_config_get_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowSettingsView',
        schema: dsh_devflow_devflow_config_get_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":687,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/config.models',
      service: 'devflow',
      namespace: 'devflow',
      method: 'config.models',
      implementation: 'configModels',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowStateRequest',
            schema: dsh_devflow_devflow_config_models_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow#devflow/config.models:result',
        schema: dsh_devflow_devflow_config_models_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":749,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/config.set',
      service: 'devflow',
      namespace: 'devflow',
      method: 'config.set',
      implementation: 'configSet',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowConfigSetRequest',
            schema: dsh_devflow_devflow_config_set_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowSettings',
        schema: dsh_devflow_devflow_config_set_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":712,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/project-add',
      service: 'devflow',
      namespace: 'devflow',
      method: 'project-add',
      implementation: 'projectAdd',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowProjectAddRequest',
            schema: dsh_devflow_devflow_project_add_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowProjectAddResult',
        schema: dsh_devflow_devflow_project_add_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":755,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/project-list-dir',
      service: 'devflow',
      namespace: 'devflow',
      method: 'project-list-dir',
      implementation: 'projectListDir',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow#devflow/project-list-dir:request',
            schema: dsh_devflow_devflow_project_list_dir_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowDirListing',
        schema: dsh_devflow_devflow_project_list_dir_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":831,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/project-pick-capability',
      service: 'devflow',
      namespace: 'devflow',
      method: 'project-pick-capability',
      implementation: 'projectPickCapability',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowPickCapabilityResult',
        schema: dsh_devflow_devflow_project_pick_capability_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":802,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/project-pick-native',
      service: 'devflow',
      namespace: 'devflow',
      method: 'project-pick-native',
      implementation: 'projectPickNative',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowPickNativeResult',
        schema: dsh_devflow_devflow_project_pick_native_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":815,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/project-remove',
      service: 'devflow',
      namespace: 'devflow',
      method: 'project-remove',
      implementation: 'projectRemove',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowProjectRemoveRequest',
            schema: dsh_devflow_devflow_project_remove_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: dsh_devflow_devflow_project_remove_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":774,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/project-scan',
      service: 'devflow',
      namespace: 'devflow',
      method: 'project-scan',
      implementation: 'projectScan',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowProjectScanRequest',
            schema: dsh_devflow_devflow_project_scan_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: dsh_devflow_devflow_project_scan_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":795,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/prompt-set',
      service: 'devflow',
      namespace: 'devflow',
      method: 'prompt-set',
      implementation: 'promptSet',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowPromptSetRequest',
            schema: dsh_devflow_devflow_prompt_set_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: dsh_devflow_devflow_prompt_set_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":669,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/prompts',
      service: 'devflow',
      namespace: 'devflow',
      method: 'prompts',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowStateRequest',
            schema: dsh_devflow_devflow_prompts_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowPromptsView',
        schema: dsh_devflow_devflow_prompts_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":660,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/resume',
      service: 'devflow',
      namespace: 'devflow',
      method: 'resume',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow#devflow/resume:request',
            schema: dsh_devflow_devflow_resume_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: dsh_devflow_devflow_resume_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":615,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/retry',
      service: 'devflow',
      namespace: 'devflow',
      method: 'retry',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow#devflow/retry:request',
            schema: dsh_devflow_devflow_retry_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowMutationResult',
        schema: dsh_devflow_devflow_retry_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":629,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/state',
      service: 'devflow',
      namespace: 'devflow',
      method: 'state',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowStateRequest',
            schema: dsh_devflow_devflow_state_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowView',
        schema: dsh_devflow_devflow_state_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":504,"column":9},
    },
    {
      id: 'dsh-devflow#devflow/submit',
      service: 'devflow',
      namespace: 'devflow',
      method: 'submit',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: 'dsh-devflow/types#DevflowSubmitRequest',
            schema: dsh_devflow_devflow_submit_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: 'dsh-devflow/types#DevflowSubmitResult',
        schema: dsh_devflow_devflow_submit_result$schema,
      },
      sourceLocation: {"file":"packages/devflow/src/index.ts","line":519,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "The pipeline service. One process-local timer drives every project partition; each partition's tick owns its state mutations with its own busy flag, and per-call AbortControllers forward panel cancels into in-flight model streams.",
        "summary": "The pipeline service.",
        "tags": [],
        "jsDoc": "/**\n * The pipeline service. One process-local timer drives every project\n * partition; each partition's tick owns its state mutations with its own\n * busy flag, and per-call AbortControllers forward panel cancels into\n * in-flight model streams.\n */",
        "key": "devflow",
        "exportName": "DevflowService",
        "members": [
          {
            "kind": "method",
            "name": "state",
            "signature": "@Remote('state') async state(request: DevflowStateRequest): Promise<DevflowView>",
            "summary": "Whole-state projection of one project partition (plus the directory).",
            "jsDoc": "/** Whole-state projection of one project partition (plus the directory). */"
          },
          {
            "kind": "method",
            "name": "submit",
            "signature": "@Remote('submit') async submit(request: DevflowSubmitRequest): Promise<DevflowSubmitResult>",
            "summary": "Drop one raw requirement or bug into one project's pool.",
            "jsDoc": "/** Drop one raw requirement or bug into one project's pool. */"
          },
          {
            "kind": "method",
            "name": "answer",
            "signature": "@Remote('answer') async answer(request: DevflowAnswerRequest): Promise<DevflowMutationResult>",
            "summary": "Answer waiting-queue or refinement questions.",
            "jsDoc": "/** Answer waiting-queue or refinement questions. */"
          },
          {
            "kind": "method",
            "name": "cancel",
            "signature": "@Remote('cancel') async cancel(request: { itemId: string }): Promise<DevflowMutationResult>",
            "summary": "Interrupt execution or collapse a waiting entry into a real pause.",
            "jsDoc": "/** Interrupt execution or collapse a waiting entry into a real pause. */"
          },
          {
            "kind": "method",
            "name": "resume",
            "signature": "@Remote('resume') async resume(request: { itemId: string }): Promise<DevflowMutationResult>",
            "summary": "Resume a paused item back into its pre-interruption lane.",
            "jsDoc": "/** Resume a paused item back into its pre-interruption lane. */"
          },
          {
            "kind": "method",
            "name": "retry",
            "signature": "@Remote('retry') async retry(request: { itemId: string }): Promise<DevflowMutationResult>",
            "summary": "Clear one item's sticky stage error (or refine cooldown).",
            "jsDoc": "/** Clear one item's sticky stage error (or refine cooldown). */"
          },
          {
            "kind": "method",
            "name": "artifact",
            "signature": "@Remote('artifact') async artifact(request: DevflowArtifactRequest): Promise<string>",
            "summary": "Read one artifact's (clipped) text for the panel viewer.",
            "jsDoc": "/** Read one artifact's (clipped) text for the panel viewer. */"
          },
          {
            "kind": "method",
            "name": "prompts",
            "signature": "@Remote('prompts') async prompts(request: DevflowStateRequest): Promise<DevflowPromptsView>",
            "summary": "Prompt-template directory of one project: defaults plus overrides.",
            "jsDoc": "/** Prompt-template directory of one project: defaults plus overrides. */"
          },
          {
            "kind": "method",
            "name": "promptSet",
            "signature": "@Remote('prompt-set') async promptSet(request: DevflowPromptSetRequest): Promise<DevflowMutationResult>",
            "summary": "Set (or clear with null) one stage's custom template for one project.",
            "jsDoc": "/** Set (or clear with null) one stage's custom template for one project. */"
          },
          {
            "kind": "method",
            "name": "configGet",
            "signature": "@Remote('config.get') async configGet(request: DevflowStateRequest): Promise<DevflowSettingsView>",
            "summary": "Unified settings read: effective document plus load warnings (D18).",
            "jsDoc": "/** Unified settings read: effective document plus load warnings (D18). */"
          },
          {
            "kind": "method",
            "name": "configSet",
            "signature": "@Remote('config.set') async configSet(request: DevflowConfigSetRequest): Promise<DevflowSettings>",
            "summary": "Unified settings write: whole-document replacement after validation (D5).",
            "jsDoc": "/**\n * Unified settings write: whole-document replacement after validation\n * (D5). Model ids are checked against the live harness catalog (the\n * models.ts real implementation — this is one of its two production\n * assembly points, D19).\n */"
          },
          {
            "kind": "method",
            "name": "configModels",
            "signature": "@Remote('config.models') async configModels(_request: DevflowStateRequest): Promise<readonly DevflowModelInfo[]>",
            "summary": "Whitelisted harness model catalog for the panel dropdown (D1/D21).",
            "jsDoc": "/** Whitelisted harness model catalog for the panel dropdown (D1/D21). */"
          },
          {
            "kind": "method",
            "name": "projectAdd",
            "signature": "@Remote('project-add') async projectAdd(request: DevflowProjectAddRequest): Promise<DevflowProjectAddResult>",
            "summary": "Add one project folder manually (also un-ignores the path).",
            "jsDoc": "/** Add one project folder manually (also un-ignores the path). */"
          },
          {
            "kind": "method",
            "name": "projectRemove",
            "signature": "@Remote('project-remove') async projectRemove(request: DevflowProjectRemoveRequest): Promise<DevflowMutationResult>",
            "summary": "Hide one project from the directory (its durable state is kept).",
            "jsDoc": "/** Hide one project from the directory (its durable state is kept). */"
          },
          {
            "kind": "method",
            "name": "projectScan",
            "signature": "@Remote('project-scan') async projectScan(_request: DevflowProjectScanRequest): Promise<DevflowMutationResult>",
            "summary": "Force a workspace rescan (the manage dialog calls this on open).",
            "jsDoc": "/** Force a workspace rescan (the manage dialog calls this on open). */"
          },
          {
            "kind": "method",
            "name": "projectPickCapability",
            "signature": "@Remote('project-pick-capability') async projectPickCapability(): Promise<DevflowPickCapabilityResult>",
            "summary": "Which folder-picking interaction the host offers for manual adds.",
            "jsDoc": "/** Which folder-picking interaction the host offers for manual adds. */"
          },
          {
            "kind": "method",
            "name": "projectPickNative",
            "signature": "@Remote('project-pick-native') async projectPickNative(): Promise<DevflowPickNativeResult>",
            "summary": "One native OS chooser round trip (null when the operator cancels).",
            "jsDoc": "/** One native OS chooser round trip (null when the operator cancels). */"
          },
          {
            "kind": "method",
            "name": "projectListDir",
            "signature": "@Remote('project-list-dir') async projectListDir(request: { path: string | null }): Promise<DevflowDirListing>",
            "summary": "One directory level for the in-app browse flow.",
            "jsDoc": "/** One directory level for the in-app browse flow. */"
          }
        ],
        "types": [
          {
            "name": "DevflowAnswer",
            "declaration": "export interface DevflowAnswer {\n    readonly q: string;\n    readonly a: string;\n}"
          },
          {
            "name": "DevflowAnswerRequest",
            "declaration": "export interface DevflowAnswerRequest {\n    readonly itemId: string;\n    readonly stage: DevflowStage | null;\n    readonly answers: readonly DevflowAnswer[];\n}"
          },
          {
            "name": "DevflowArtifactRequest",
            "declaration": "export interface DevflowArtifactRequest {\n    readonly itemId: string;\n    readonly name: 'design' | 'plan' | 'report' | 'reviews';\n}"
          },
          {
            "name": "DevflowConfigSetRequest",
            "declaration": "export interface DevflowConfigSetRequest {\n    readonly project: string | null;\n    readonly settings: DevflowSettings;\n}"
          },
          {
            "name": "DevflowDirEntry",
            "declaration": "export interface DevflowDirEntry {\n    readonly name: string;\n    readonly path: string;\n    readonly hidden: boolean;\n}"
          },
          {
            "name": "DevflowDirListing",
            "declaration": "export interface DevflowDirListing {\n    readonly path: string;\n    readonly home: string;\n    readonly crumbs: readonly DevflowDirEntry[];\n    readonly entries: readonly DevflowDirEntry[];\n    readonly truncated: boolean;\n}"
          },
          {
            "name": "DevflowItemStatus",
            "declaration": "export type DevflowItemStatus = 'raw' | 'refining' | 'needs-user' | 'ready' | 'active' | 'done' | 'rejected' | 'paused';"
          },
          {
            "name": "DevflowItemView",
            "declaration": "export interface DevflowItemView {\n    readonly id: string;\n    readonly kind: 'requirement' | 'bug';\n    readonly title: string;\n    readonly status: DevflowItemStatus;\n    readonly size: DevflowSize | null;\n    readonly score: DevflowScore | null;\n    readonly running: boolean;\n    readonly note: string | null;\n    readonly preview: string;\n    readonly rejectReason: string;\n    readonly questions: readonly DevflowQuestion[] | null;\n    readonly waitingStage: DevflowStage | null;\n    readonly stage: DevflowStage | null;\n    readonly round: number;\n    readonly error: string | null;\n    readonly workspaceKind: 'main' | 'worktree' | null;\n    readonly workspacePath: string | null;\n    readonly workspaceBranch: string | null;\n    readonly resourceWaiting: 'workspace' | 'worktree' | null;\n    readonly reportFile: string | null;\n    readonly pumpRunning: boolean;\n    readonly pumpWaitingUser: boolean;\n    readonly pumpWaitingApproval: boolean;\n    readonly pumpSessionId: string | null;\n    readonly log: readonly DevflowLogLine[];\n}"
          },
          {
            "name": "DevflowLogLine",
            "declaration": "export interface DevflowLogLine {\n    readonly n: number;\n    readonly note: string;\n}"
          },
          {
            "name": "DevflowModelInfo",
            "declaration": "export interface DevflowModelInfo {\n    readonly id: string;\n    readonly label: string;\n}"
          },
          {
            "name": "DevflowMutationResult",
            "declaration": "export interface DevflowMutationResult {\n    readonly ok: boolean;\n    readonly reason?: string;\n}"
          },
          {
            "name": "DevflowPickCapabilityResult",
            "declaration": "export interface DevflowPickCapabilityResult {\n    readonly kind: 'native' | 'browse' | 'none';\n}"
          },
          {
            "name": "DevflowPickNativeResult",
            "declaration": "export interface DevflowPickNativeResult {\n    readonly path: string | null;\n}"
          },
          {
            "name": "DevflowProjectAddRequest",
            "declaration": "export interface DevflowProjectAddRequest {\n    readonly path: string;\n}"
          },
          {
            "name": "DevflowProjectAddResult",
            "declaration": "export interface DevflowProjectAddResult {\n    readonly ok: boolean;\n    readonly reason?: string;\n    readonly key: string | null;\n}"
          },
          {
            "name": "DevflowProjectInfo",
            "declaration": "export interface DevflowProjectInfo {\n    readonly key: string;\n    readonly name: string;\n    readonly root: string;\n    readonly origin: DevflowProjectOrigin;\n}"
          },
          {
            "name": "DevflowProjectOrigin",
            "declaration": "export type DevflowProjectOrigin = 'workspace' | 'scan' | 'manual';"
          },
          {
            "name": "DevflowProjectRemoveRequest",
            "declaration": "export interface DevflowProjectRemoveRequest {\n    readonly key: string;\n}"
          },
          {
            "name": "DevflowProjectScanRequest",
            "declaration": "export interface DevflowProjectScanRequest {\n    readonly rescan: boolean;\n}"
          },
          {
            "name": "DevflowPromptSetRequest",
            "declaration": "export interface DevflowPromptSetRequest {\n    readonly stage: string;\n    readonly template: string | null;\n    readonly project: string | null;\n}"
          },
          {
            "name": "DevflowPromptsView",
            "declaration": "export interface DevflowPromptsView {\n    readonly custom: Record<string, string>;\n    readonly defaults: Record<string, string>;\n    readonly vars: Record<string, readonly string[]>;\n}"
          },
          {
            "name": "DevflowPumpView",
            "declaration": "export interface DevflowPumpView {\n    readonly enabled: boolean;\n    readonly available: boolean;\n    readonly activeCount: number;\n    readonly maxConcurrent: number;\n    readonly model: string | null;\n}"
          },
          {
            "name": "DevflowQuestion",
            "declaration": "export interface DevflowQuestion {\n    readonly id?: string;\n    readonly q: string;\n    readonly options: readonly DevflowQuestionOption[];\n    readonly recommend?: string;\n}"
          },
          {
            "name": "DevflowQuestionOption",
            "declaration": "export interface DevflowQuestionOption {\n    readonly label: string;\n    readonly desc: string;\n}"
          },
          {
            "name": "DevflowScore",
            "declaration": "export interface DevflowScore {\n    readonly value: number;\n    readonly completeness: number;\n}"
          },
          {
            "name": "DevflowSettings",
            "declaration": "export interface DevflowSettings {\n    readonly version: 1;\n    readonly stageModels: { readonly [stage: string]: string; };\n    readonly pump?: { readonly enabled: boolean; readonly model: string; };\n}"
          },
          {
            "name": "DevflowSettingsView",
            "declaration": "export interface DevflowSettingsView {\n    readonly settings: DevflowSettings;\n    readonly warnings: readonly string[];\n}"
          },
          {
            "name": "DevflowSize",
            "declaration": "export type DevflowSize = 'small' | 'medium' | 'large';"
          },
          {
            "name": "DevflowStage",
            "declaration": "export type DevflowStage = 'design' | 'plan' | 'review-dp' | 'implement' | 'code-review' | 'fix-code' | 'verify' | 'merge' | 'report';"
          },
          {
            "name": "DevflowStateRequest",
            "declaration": "export interface DevflowStateRequest {\n    readonly project: string | null;\n}"
          },
          {
            "name": "DevflowSubmitRequest",
            "declaration": "export interface DevflowSubmitRequest {\n    readonly kind: 'requirement' | 'bug';\n    readonly text: string;\n    readonly project: string | null;\n}"
          },
          {
            "name": "DevflowSubmitResult",
            "declaration": "export interface DevflowSubmitResult {\n    readonly ok: boolean;\n    readonly id: string;\n}"
          },
          {
            "name": "DevflowView",
            "declaration": "export interface DevflowView {\n    readonly busy: boolean;\n    readonly note: string | null;\n    readonly error: string | null;\n    readonly project: string | null;\n    readonly projects: readonly DevflowProjectInfo[];\n    readonly ignoredRoots: readonly string[];\n    readonly waitingTotal: number;\n    readonly pump: DevflowPumpView;\n    readonly items: readonly DevflowItemView[];\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
